data:
  dataset: "shakespeare"
  split: 0.9
  num_workers: 0

model:
  model_name: "bigram"
  compile: true
  model_kwargs: {}

trainer:
  seed: 42
  auto_restart: true
  batch_size: 32
  eval_batch_size: 4
  max_steps: 1000
  val_interval: 100
  lr_config:
    scheduler: "cosine"
    lr: 0.01
    min_lr_ratio: 0.1
  betas: [0.9, 0.95]
  warmup_steps: 100
  weight_decay: 0.1
  grad_clip: 1.0
  precision: "bf16"
  use_progress_bar: true
  logger: ["tensorboard"]
  log_interval: 10
  log_dir: null
  base_dir: "runs/"
  run_name: ""
  use_profiler: false
  profiler_config:
    wait: 1
    warmup: 1
    active: 3
    repeat: 0
  ckpt_path: null
  save_interval: 0

distributed:
  device: "auto"
  distributed: "single"
  rank: 0
  world_size: 1
