
data:
  dataset: "shakespeare"
  split: 0.9
  num_workers: 0

model:
  model_name: "minigpt"
  model_kwargs:
    block_size: 128
    n_layer: 4
    n_head: 4
    n_embed: 256
    hidden_dim: 1024
    ffn_dropout: 0.1
    attn_dropout: 0.1
    residual_dropout: 0.1

trainer:
  auto_restart: true
  batch_size: 64
  max_epochs: 1
  max_steps: 500
  val_interval: 100
  lr: 0.0003
  lr_config:
    scheduler: "cosine"
    min_lr_ratio: 0.1
    gamma: 0.0  # Exponential decay
    power: 0.0  # Polynomial decay
    cycle_steps: 0.0  # cosine restart
    one_cycle_pct: 0.0  # one cycle
  betas: [0.9, 0.95]
  warmup_steps: 200
  weight_decay: 0.01
  grad_clip: 1.0
  precision: "fp16"
  use_fp16: false
  use_progress_bar: true
  logger: ["tensorboard"]
  log_dir: "runs/"
  log_interval: 10
  use_profiler: false
  profiler_wait: 1
  profiler_warmup: 1
  profiler_active: 3
  profiler_repeat: 2
  save_path: "checkpoints/mini_gpt"
  save_interval: 0

experimental:
  seed: 42
  compile: false
  experiment_name: ""

distributed:
  device: "cuda"
  rank: 0
  world_size: 1
  distributed: "single"
